# Ansible playbook for provisining the VMs
# see http://docs.ansible.com/ to know about Ansible.

---
- hosts: all
  sudo: true
  tasks:
    - name: ensure apt is up-to-date
      apt: update_cache=yes

    - name: ensure required apt packages is installed
      apt: pkg={{item}} state=present
      with_items:
        - apache2
        - postgresql
        - python-psycopg2

    - name: create vagrant user for postgres
      postgresql_user: name=vagrant role_attr_flags=SUPERUSER
      sudo_user: postgres

     
